In [112]:
## Importing train data
import pandas as pd
import numpy as np
train_data=pd.read_csv("E:\\Analytic vidya\\India\\train.csv")
train_data.head()

loan_id source       financial_institution  interest_rate  \
0  268055008619      Z  Turner, Baldwin and Rhodes          4.250   
1  672831657627      Y  Swanson, Newton and Miller          4.875   
2  742515242108      Z              Thornton-Davis          3.250   
3  601385667462      X                       OTHER          4.750   
4  273870029961      X                       OTHER          4.750   

   unpaid_principal_bal  loan_term origination_date first_payment_date  \
0                214000        360       2012-03-01            05/2012   
1                144000        360       2012-01-01            03/2012   
2                366000        180       2012-01-01            03/2012   
3                135000        360       2012-02-01            04/2012   
4                124000        360       2012-02-01            04/2012   

   loan_to_value  number_of_borrowers ...   m4  m5 m6  m7  m8  m9  m10  m11  \
0             95                  1.0 ...    0   0  0   1   0   0    0    0   
1             72                  1.0 ...    0   0  0   0   0   0    0    1   
2             49                  1.0 ...    0   0  0   0   0   0    0    0   
3             46                  2.0 ...    0   0  0   0   0   1    1    1   
4             80                  1.0 ...    3   4  5   6   7   8    9   10   

   m12  m13  
0    0    1  
1    0    1  
2    0    1  
3    1    1  
4   11    1  

[5 rows x 29 columns]

In [113]:
## Importing Test data
test_data1=pd.read_csv("E:\\Analytic vidya\\India\\test.csv")
test_data1.head()

loan_id source      financial_institution  interest_rate  \
0        1      Y              Browning-Hart          3.875   
1        2      X                      OTHER          4.500   
2        3      Y                      OTHER          4.500   
3        4      X  Miller, Mcclure and Allen          4.125   
4        5      X              Browning-Hart          3.250   

   unpaid_principal_bal  loan_term origination_date first_payment_date  \
0                417000        360         01/02/12             Apr-12   
1                113000        360         01/02/12             Apr-12   
2                 72000        360         01/01/12             Mar-12   
3                123000        180         01/02/12             Apr-12   
4                166000        180         01/02/12             Apr-12   

   loan_to_value  number_of_borrowers ...   m3  m4 m5  m6  m7  m8  m9  m10  \
0             75                    1 ...    0   0  0   0   0   0   0    0   
1             80                    2 ...    0   0  0   0   0   0   0    0   
2             75                    1 ...    0   0  0   0   0   0   0    0   
3             41                    2 ...    0   0  0   0   0   0   0    0   
4             53                    2 ...    0   0  0   0   0   0   0    0   

   m11  m12  
0    0    0  
1    0    0  
2    0    0  
3    0    0  
4    0    0  

[5 rows x 28 columns]

In [42]:
#data visualization (Data preprocessing)
#train_data.source.value_counts()
corr=train_data.corr()
import seaborn as sns
#x=sns.heatmap(corr, xticklabels=corr.columns,yticklabels=corr.columns, vmin=-1, vmax=1, center=0,cmap=sns.diverging_palette(20, 220, n=200),square=True)
#x.set_xticklabels(x.get_xticklabels(),rotation=45,horizontalalignment='right');

In [43]:
train_data["m13"].value_counts()
#train_mod.isnull().sum()
#train_mod.financial_institution.unique()

0    115422
1       636
Name: m13, dtype: int64

In [6]:
### For data balancing  (without SMORT)

#m130=train_data[train_data["m13"] == 0].sample(75000)
#m131=train_data[train_data["m13"] == 1]
#m130.shape

(75000, 29)

In [9]:
### For data balancing (without SMORT)

#m131=pd.concat([m131,m131,m131,m131,m131,m131,m131,m131,m131,m131,m131,m131,m131,m131,m131,m131,m131,m131,m131,m131])
#m131=pd.concat([m131,m131,m131,m131,m131,m131,m131,m131])
#m131=m131.sample(75000)
#m131.shape

(75000, 29)

In [10]:
### For data balancing (without SMORT)

#train_mod=pd.concat([m131,m130])
#train_mod.head(2)
#train_mod.shape

(150000, 29)

In [44]:
#Dropping "loan_id since it is just the sequence value"

#train_data.isnull().sum()   ## checking if any entry is null
train_mod=train_data.drop(["loan_id"],axis=1)
print (train_mod.shape)
train_mod.head(3)

(116058, 28)


source       financial_institution  interest_rate  unpaid_principal_bal  \
0      Z  Turner, Baldwin and Rhodes          4.250                214000   
1      Y  Swanson, Newton and Miller          4.875                144000   
2      Z              Thornton-Davis          3.250                366000   

   loan_term origination_date first_payment_date  loan_to_value  \
0        360       2012-03-01            05/2012             95   
1        360       2012-01-01            03/2012             72   
2        180       2012-01-01            03/2012             49   

   number_of_borrowers  debt_to_income_ratio ...   m4 m5  m6  m7  m8  m9  m10  \
0                  1.0                  22.0 ...    0  0   0   1   0   0    0   
1                  1.0                  44.0 ...    0  0   0   0   0   0    0   
2                  1.0                  33.0 ...    0  0   0   0   0   0    0   

   m11  m12  m13  
0    0    0    1  
1    1    0    1  
2    0    0    1  

[3 rows x 28 columns]

In [46]:
train_mod.loan_purpose.value_counts()
train_mod.m13.value_counts()

0    115422
1       636
Name: m13, dtype: int64

In [47]:
## Label Encoding

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le1=LabelEncoder()
le2=LabelEncoder()
le3=LabelEncoder()
le4=LabelEncoder()
train_mod["source"]=le.fit_transform(train_mod["source"])
train_mod["loan_purpose"]=le1.fit_transform(train_mod["loan_purpose"])
train_mod["financial_institution"]=le2.fit_transform(train_mod["financial_institution"])
train_mod["origination_date"]=le3.fit_transform(train_mod["origination_date"])
train_mod["first_payment_date"]=le4.fit_transform(train_mod["first_payment_date"])
train_mod.head(2)

source  financial_institution  interest_rate  unpaid_principal_bal  \
0       2                     18          4.250                214000   
1       1                     15          4.875                144000   

   loan_term  origination_date  first_payment_date  loan_to_value  \
0        360                 2                   3             95   
1        360                 0                   1             72   

   number_of_borrowers  debt_to_income_ratio ...   m4  m5  m6  m7  m8  m9  \
0                  1.0                  22.0 ...    0   0   0   1   0   0   
1                  1.0                  44.0 ...    0   0   0   0   0   0   

   m10  m11  m12  m13  
0    0    0    0    1  
1    0    1    0    1  

[2 rows x 28 columns]

In [142]:
'''
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
train_mod1=sc.fit_transform(train_mod)
print (type(train_mod1))
new_mod=pd.DataFrame(data=train_mod1,columns=train_mod.columns)
print (new_mod.shape)
new_mod.head()
'''

'\nfrom sklearn.preprocessing import StandardScaler\nsc=StandardScaler()\ntrain_mod1=sc.fit_transform(train_mod)\nprint (type(train_mod1))\nnew_mod=pd.DataFrame(data=train_mod1,columns=train_mod.columns)\nprint (new_mod.shape)\nnew_mod.head()\n'

In [50]:
## Splitting Label data

X_sc=train_mod.iloc[:,train_mod.columns!='m13']
print (X_sc.shape)
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X=sc.fit_transform(X_sc)
print (type(X))
new_mod=pd.DataFrame(data=X,columns=X_sc.columns)
print (new_mod.shape)
new_mod.head()
Y=train_mod["m13"]
Y.shape

(116058, 27)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int32, int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)


<class 'numpy.ndarray'>
(116058, 27)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int32, int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


(116058,)

In [52]:
new_mod.head()

source  financial_institution  interest_rate  unpaid_principal_bal  \
0  2.020724               2.579894       0.826517              0.050345   
1  0.601706               1.905869       2.182212             -0.560025   
2  2.020724               2.355219      -1.342595              1.375719   
3 -0.817313               0.333146       1.911073             -0.638501   
4 -0.817313               0.333146       1.911073             -0.734416   

   loan_term  origination_date  first_payment_date  loan_to_value  \
0   0.754428          1.910366            1.874676       1.594300   
1   0.754428         -1.035598           -1.030689       0.264177   
2  -1.250874         -1.035598           -1.030689      -1.065945   
3   0.754428          0.437384            0.421994      -1.239439   
4   0.754428          0.437384            0.421994       0.726829   

   number_of_borrowers  debt_to_income_ratio    ...             m3         m4  \
0            -1.207529             -0.898419    ...      -0.035599  -0.035069   
1            -1.207529              1.362454    ...      -0.035599  -0.035069   
2            -1.207529              0.232018    ...      -0.035599  -0.035069   
3             0.828137              1.362454    ...      -0.035599  -0.035069   
4            -1.207529              1.259687    ...      36.047883  48.226620   

         m5         m6         m7         m8         m9        m10        m11  \
0  -0.04275  -0.039070   9.863609  -0.042652  -0.041791  -0.044583  -0.043642   
1  -0.04275  -0.039070  -0.041221  -0.042652  -0.041791  -0.044583   6.095719   
2  -0.04275  -0.039070  -0.041221  -0.042652  -0.041791  -0.044583  -0.043642   
3  -0.04275  -0.039070  -0.041221  -0.042652   7.756016   6.692613   6.095719   
4  48.36153  57.069319  59.387759  61.834283  62.340670  60.590177  61.349964   

         m12  
0  -0.045276  
1  -0.045276  
2  -0.045276  
3   5.568680  
4  61.708245  

[5 rows x 27 columns]

In [17]:
## Splitting Test Train data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(new_mod,Y,test_size=0.25)
y_train.shape

(112500,)

In [66]:
#Using SMOTE for Balancing Data

from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state=2)
x_train_res, y_train_res = sm.fit_sample(x_train, y_train.ravel())
print (sum(y_train_res==0))
print (sum(y_train_res==1))
sum(y_train==1)

56384
56384


56116

In [74]:
# Only for SMORT splitting Test Train data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_train_res,y_train_res,test_size=0.25)
print (x_train.shape)
y_train.shape

#x_train=x_train_res.copy()
#y_train=y_train_res.copy()
y_train_res.shape

(84576, 27)


(112768,)

In [75]:
from sklearn.metrics import accuracy_score,confusion_matrix,f1_score
from xgboost import XGBClassifier
xg=XGBClassifier()
xg.fit(x_train,y_train)
pred_xg=xg.predict(x_test)
print (accuracy_score(y_test,pred_xg))
print (confusion_matrix(y_test,pred_xg))
f1_score(y_test,pred_xg)

0.8458073212258796
[[12945  1143]
 [ 3204 10900]]


0.833747657475045

In [76]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,f1_score,confusion_matrix
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)
pred=dt.predict(x_test)
print (accuracy_score(y_test,pred))
print (confusion_matrix(y_test,pred))
f1_score(y_test,pred)

0.9958498864926221
[[13971   117]
 [    0 14104]]


0.9958693733451015

In [77]:
##Logistic Regression
from sklearn.metrics import confusion_matrix,f1_score,accuracy_score
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression().fit(x_train, y_train)
y_pred = clf.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
acc_lr = accuracy_score(y_test, y_pred)
print (acc_lr)
print (confusion_matrix(y_test,y_pred))
print (f1_score(y_test, y_pred,average=None))
f1_score(y_test,y_pred)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.8325411464245176
[[13001  1087]
 [ 3634 10470]]
[0.84633662 0.81602432]


0.8160243170570126

In [78]:
from sklearn.neural_network import MLPClassifier
ml = MLPClassifier(hidden_layer_sizes=(100, 100, 100,))
ml.fit(x_train, y_train)
print("Score: ", ml.score(x_test, y_test))
y_pred_ml= ml.predict(x_test)
#y_pred_proba = ml.predict_proba(x_test,y_pred_ml)
print("F1 score is: {}".format(f1_score(y_test, y_pred_ml)))
#print("AUC Score is: {}".format(roc_auc_score(y_test, y_pred_proba)))

Score:  0.9943246311010215
F1 score is: 0.9943498834663466


In [79]:
## Using RF on multiple n_estimaters

from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(n_estimators=400)
rfc.fit(x_train,y_train)
pred2=rfc.predict(x_test)
print (accuracy_score(y_test,pred2))
print (confusion_matrix(y_test,pred2))
f1_score(y_test,pred2)

0.9989358683314415
[[14058    30]
 [    0 14104]]


0.9989376018131596

In [80]:
from sklearn.ensemble import RandomForestClassifier
rfc1=RandomForestClassifier(n_estimators=300)
rfc1.fit(x_train,y_train)
pred2=rfc1.predict(x_test)
print (accuracy_score(y_test,pred2))
print (confusion_matrix(y_test,pred2))
f1_score(y_test,pred2)

0.9989358683314415
[[14058    30]
 [    0 14104]]


0.9989376018131596

In [81]:
from sklearn.ensemble import RandomForestClassifier
rfc2=RandomForestClassifier(n_estimators=200)
rfc2.fit(x_train,y_train)
pred2=rfc1.predict(x_test)
print (accuracy_score(y_test,pred2))
print (confusion_matrix(y_test,pred2))
f1_score(y_test,pred2)

0.9989358683314415
[[14058    30]
 [    0 14104]]


0.9989376018131596

In [ ]:
##SVC (commenting because causing more time to load)
"""
from sklearn.svm import SVC
sv=SVC()
sv.fit(x_train,y_train)
y_pred3=sv.predict(x_test)
acc_svc=accuracy_score(y_test, y_pred3)
print (acc_svc)
print (f1_score(y_test, y_pred3,average=None))
f1_score(y_test,y_pred3)
"""

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [82]:
from sklearn.linear_model import RidgeClassifier
rc=RidgeClassifier()
rc.fit(x_train,y_train)
pred4=rc.predict(x_test)
print (accuracy_score(y_test,pred4))
f1_score(y_test,pred4)

0.7836265607264472


0.7732173395791508

In [83]:
## Loading Test Dataset
import pandas as pd
import numpy as np
test_data=pd.read_csv("E:\\Analytic vidya\\India\\test.csv")
test_data.head(3)

loan_id source financial_institution  interest_rate  unpaid_principal_bal  \
0        1      Y         Browning-Hart          3.875                417000   
1        2      X                 OTHER          4.500                113000   
2        3      Y                 OTHER          4.500                 72000   

   loan_term origination_date first_payment_date  loan_to_value  \
0        360         01/02/12             Apr-12             75   
1        360         01/02/12             Apr-12             80   
2        360         01/01/12             Mar-12             75   

   number_of_borrowers ...   m3  m4 m5  m6  m7  m8  m9  m10  m11  m12  
0                    1 ...    0   0  0   0   0   0   0    0    0    0  
1                    2 ...    0   0  0   0   0   0   0    0    0    0  
2                    1 ...    0   0  0   0   0   0   0    0    0    0  

[3 rows x 28 columns]

In [85]:
#test_data.isnull().sum()  ## no null entry
test_mod=test_data.drop(["loan_id"],axis=1)
test_mod.head(3)

source financial_institution  interest_rate  unpaid_principal_bal  \
0      Y         Browning-Hart          3.875                417000   
1      X                 OTHER          4.500                113000   
2      Y                 OTHER          4.500                 72000   

   loan_term origination_date first_payment_date  loan_to_value  \
0        360         01/02/12             Apr-12             75   
1        360         01/02/12             Apr-12             80   
2        360         01/01/12             Mar-12             75   

   number_of_borrowers  debt_to_income_ratio ...   m3 m4  m5  m6  m7  m8  m9  \
0                    1                    20 ...    0  0   0   0   0   0   0   
1                    2                    33 ...    0  0   0   0   0   0   0   
2                    1                    34 ...    0  0   0   0   0   0   0   

   m10  m11  m12  
0    0    0    0  
1    0    0    0  
2    0    0    0  

[3 rows x 27 columns]

In [86]:
from sklearn.preprocessing import LabelEncoder
le5=LabelEncoder()
le6=LabelEncoder()
le7=LabelEncoder()
le8=LabelEncoder()
le9=LabelEncoder()
test_mod["source"]=le5.fit_transform(test_mod["source"])
test_mod["loan_purpose"]=le5.fit_transform(test_mod["loan_purpose"])
test_mod["financial_institution"]=le6.fit_transform(test_mod["financial_institution"])
test_mod["origination_date"]=le7.fit_transform(test_mod["origination_date"])
test_mod["first_payment_date"]=le8.fit_transform(test_mod["first_payment_date"])
print (test_mod.shape)
test_mod.head(2)

(35866, 27)


source  financial_institution  interest_rate  unpaid_principal_bal  \
0       1                      1          3.875                417000   
1       0                      8          4.500                113000   

   loan_term  origination_date  first_payment_date  loan_to_value  \
0        360                 1                   0             75   
1        360                 1                   0             80   

   number_of_borrowers  debt_to_income_ratio ...   m3  m4  m5  m6  m7  m8  m9  \
0                    1                    20 ...    0   0   0   0   0   0   0   
1                    2                    33 ...    0   0   0   0   0   0   0   

   m10  m11  m12  
0    0    0    0  
1    0    0    0  

[2 rows x 27 columns]

In [87]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
test_mod1=sc.fit_transform(test_mod)
print (type(test_mod1))
new_mod_test=pd.DataFrame(data=test_mod1,columns=test_mod.columns)
print (new_mod_test.shape)
new_mod_test.head()

<class 'numpy.ndarray'>
(35866, 27)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int32, int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int32, int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


source  financial_institution  interest_rate  unpaid_principal_bal  \
0  0.602875              -1.225614       0.004669              1.826422   
1 -0.818269               0.339566       1.361798             -0.827206   
2  0.602875               0.339566       1.361798             -1.185097   
3 -0.818269              -0.107628       0.547520             -0.739916   
4 -0.818269              -1.225614      -1.352460             -0.364567   

   loan_term  origination_date  first_payment_date  loan_to_value  \
0   0.748843          0.441175           -1.038044       0.441346   
1   0.748843          0.441175           -1.038044       0.731259   
2   0.748843         -1.043316            0.693767       0.441346   
3  -1.266889          0.441175           -1.038044      -1.530069   
4  -1.266889          0.441175           -1.038044      -0.834276   

   number_of_borrowers  debt_to_income_ratio    ...           m3        m4  \
0            -1.216630             -1.106607    ...    -0.034339 -0.033889   
1             0.821943              0.230015    ...    -0.034339 -0.033889   
2            -1.216630              0.332833    ...    -0.034339 -0.033889   
3             0.821943             -0.695338    ...    -0.034339 -0.033889   
4             0.821943             -1.929143    ...    -0.034339 -0.033889   

         m5        m6        m7        m8        m9       m10       m11  \
0 -0.037684 -0.035395 -0.038985 -0.039618 -0.043357 -0.045734 -0.043561   
1 -0.037684 -0.035395 -0.038985 -0.039618 -0.043357 -0.045734 -0.043561   
2 -0.037684 -0.035395 -0.038985 -0.039618 -0.043357 -0.045734 -0.043561   
3 -0.037684 -0.035395 -0.038985 -0.039618 -0.043357 -0.045734 -0.043561   
4 -0.037684 -0.035395 -0.038985 -0.039618 -0.043357 -0.045734 -0.043561   

        m12  
0 -0.045659  
1 -0.045659  
2 -0.045659  
3 -0.045659  
4 -0.045659  

[5 rows x 27 columns]

In [105]:
#Predicting m13 from test data and creating submission file(creating using multiple RF's)

print (new_mod_test.shape)
test_pred=rfc2.predict(new_mod_test)
submission=pd.DataFrame(test_pred)
#submission.insert(0,'unique_hash',test_data["unique_hash"])
submission.columns=["m13"]
submission.insert(0,'loan_id',test_data1['loan_id'])
submission=submission.round(0)
submission.head()

(35866, 27)


loan_id  m13
0        1    0
1        2    0
2        3    0
3        4    0
4        5    0

In [114]:
print (submission.m13.value_counts())  ## checking the predicted m13 value

## creating submission_file
submission.to_csv('sample_submission.csv',index=False)

0    35703
1      163
Name: m13, dtype: int64
